---
title: "Missing data patterns"
author: "David Gutiérrez-Duque"
output: pdf_document
---
# Data set example

```{r, include=FALSE}
data_example <- data.frame(ID = 1:6, Largo = c(13.47, 17.58, 10.33, 10.12, 18.09, 8.35), Ancho = c(4.86, 6.87, 4.19, 3.92, 6.44, 2.29), Forma = c("Ovada", "Elíptica", "Ovada", "Elíptica", "Elíptica", "Elíptica"), Clase = factor(c(1, 2, 1, 3, 2, 3)))
```

```{r, echo=FALSE}
print(data_example)
```
## Univariate Nonresponse
```{r, echo=FALSE}
na_univar <- data_example
na_univar$Clase <- replace(data_example$Clase, 5:6, NA)
print(na_univar)
```

## Multivariate Two Patterns
```{r, echo=FALSE}
na_multivar <- data_example
na_multivar$Largo <- replace(data_example$Largo, 2:3, NA)
na_multivar$Ancho <- replace(data_example$Ancho, 2:3, NA)
na_multivar$Clase <- replace(data_example$Clase, 2:3, NA)
print(na_multivar)
```

## Monotone pattern
```{r, echo=FALSE}
na_monotone <- data_example
na_monotone$Ancho <- replace(data_example$Ancho, 6, NA)
na_monotone$Forma <- replace(data_example$Forma, 5:6, NA)
na_monotone$Clase <- replace(data_example$Clase, 4:6, NA)
print(na_monotone)
```

## General pattern
```{r, echo=FALSE}
na_general <- data_example
na_general$Largo <- replace(data_example$Largo, 3, NA)
na_general$Ancho <- replace(data_example$Ancho, 4:5, NA)
na_general$Forma <- replace(data_example$Forma, c(1,5), NA)
print(na_general)
```